(function(global){'use strict';
  var MODE_KEY='superari.workMode',DEVICES_KEY='superari.devices',DISCOVERED_KEY='superari.discovered';
  var STATUS={yok:'yok',bagli:'bagli',kopuk:'kopuk',arizali:'arizali'};
  var TIP_LABELS={tarti:'Tartı',isi_nem:'Sıcaklık/Nem',ir:'IR',ses_titresim:'Ses/Titreşim',gateway:'Gateway (Wi‑Fi / hücresel)',kamera_arilik:'Arılık kamerası',kamera_merkez:'Arılık kamerası',kamera_kovan:'Kovan kamerası',role_hub:'Wireless röle / hub'};
  var DEMO_SEED=[
    {id:'demo-gw-a1',tip:'gateway',apiaryId:'a1',apiaryName:'Kayaköy Ana Arılık',hiveId:null,hiveName:null,status:'bagli',battery:null,lastMins:1,channels:['Gateway']},
    {id:'demo-cam-a1',tip:'kamera_arilik',apiaryId:'a1',apiaryName:'Kayaköy Ana Arılık',hiveId:null,hiveName:null,status:'bagli',battery:88,lastMins:2,channels:['Arılık kamerası']},
    {id:'demo-tarti-101',tip:'tarti',apiaryId:'a1',apiaryName:'Kayaköy Ana Arılık',hiveId:101,hiveName:'Kovan 101',status:'bagli',battery:72,lastMins:4,channels:['Tartı']},
    {id:'demo-isi-101',tip:'isi_nem',apiaryId:'a1',apiaryName:'Kayaköy Ana Arılık',hiveId:101,hiveName:'Kovan 101',status:'bagli',battery:68,lastMins:3,channels:['Sıcaklık/Nem']},
    {id:'demo-isi-118-kopuk',tip:'isi_nem',apiaryId:'a1',apiaryName:'Kayaköy Ana Arılık',hiveId:118,hiveName:'Kovan 118',status:'kopuk',battery:41,lastMins:210,channels:['Sıcaklık/Nem']},
    {id:'demo-tarti-211-arizali',tip:'tarti',apiaryId:'a2',apiaryName:'Tortum Yayla Arılığı',hiveId:211,hiveName:'Kovan 211',status:'arizali',battery:4,lastMins:15,channels:['Tartı']},
    {id:'demo-cam-a2-kopuk',tip:'kamera_arilik',apiaryId:'a2',apiaryName:'Tortum Yayla Arılığı',hiveId:null,hiveName:null,status:'kopuk',battery:52,lastMins:320,channels:['Arılık kamerası']},
    {id:'demo-cam-kovan-118-arizali',tip:'kamera_kovan',apiaryId:'a1',apiaryName:'Kayaköy Ana Arılık',hiveId:118,hiveName:'Kovan 118',status:'arizali',battery:2,lastMins:95,channels:['Kovan kamerası']},
    {id:'demo-ir-102',tip:'ir',apiaryId:'a1',apiaryName:'Kayaköy Ana Arılık',hiveId:102,hiveName:'Kovan 102',status:'bagli',battery:77,lastMins:6,channels:['IR']},
    {id:'demo-ses-204',tip:'ses_titresim',apiaryId:'a2',apiaryName:'Tortum Yayla Arılığı',hiveId:204,hiveName:'Kovan 204',status:'bagli',battery:61,lastMins:8,channels:['Ses/Titreşim']}
  ];
  function getMode(){try{var m=localStorage.getItem(MODE_KEY);if(m==='live'||m==='demo')return m;}catch(e){}return'demo';}
  function setMode(m){var n=m==='live'?'live':'demo';try{localStorage.setItem(MODE_KEY,n);}catch(e){}try{if(typeof document!=='undefined')document.documentElement.setAttribute('data-work-mode',n);}catch(e2){}try{window.dispatchEvent(new CustomEvent('superari:workMode',{detail:{mode:n}}));}catch(e3){}return n;}
  function isDemo(){return getMode()==='demo';} function isLive(){return getMode()==='live';}
  function statusLabel(s){return({yok:'Yok',bagli:'Bağlı',kopuk:'Kopuk',arizali:'Arızalı'})[s]||'Yok';}
  function statusTone(s){return s===STATUS.bagli?'status-bagli':s===STATUS.kopuk?'status-kopuk':s===STATUS.arizali?'status-arizali':'status-yok';}
  function statusAnaTone(s){return s===STATUS.bagli?'green':s===STATUS.arizali?'red':'tan';}
  function tipLabel(t){return TIP_LABELS[t]||t||'Cihaz';}
  function isCameraTip(t){t=String(t||'').toLowerCase();return t.indexOf('kamera')!==-1||t==='merkezi_kamera'||t==='kovan_kamerasi';}
  function isApiaryTip(t){return t==='kamera_arilik'||t==='kamera_merkez'||t==='gateway'||t==='role_hub';}
  function readArray(k){try{var a=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(a)?a:[];}catch(e){return[];}}
  function names(r){var D=global.SuperAriDemo,h=r.hiveId!=null?r.hiveId:null,a=r.apiaryId!=null?r.apiaryId:null,hv=null,ap=null;if(h!=null&&D&&D.hiveById){hv=D.hiveById(h);if(hv&&a==null)a=hv.apiaryId;}if(a!=null&&D&&D.apiaryById)ap=D.apiaryById(a);return{hiveId:h,hiveName:hv?(hv.name||'Kovan '+hv.id):(h!=null?'Kovan '+h:null),apiaryId:a!=null?String(a):'none',apiaryName:ap?(ap.name||ap.place||'Arılık'):(a?String(a):'—')};}
  function normalize(r,source){if(!r)return null;var t=r.tip||r.type||'',n=names(r),s=r.status||STATUS.bagli;if(s!==STATUS.bagli&&s!==STATUS.kopuk&&s!==STATUS.arizali&&s!==STATUS.yok)s=STATUS.bagli;var k=isCameraTip(t)?'kamera':'paket';return{id:r.id||(source+'-'+t+'-'+(n.hiveId||n.apiaryId||'x')),tip:t,typeLabel:tipLabel(t),kind:k,source:source||'user',status:s,hiveId:n.hiveId,hiveName:n.hiveName||(k==='kamera'?tipLabel(t):'Cihaz'),apiaryId:n.apiaryId,apiaryName:n.apiaryName,battery:r.battery!=null?r.battery:null,lastMins:r.lastMins!=null?r.lastMins:null,channels:r.channels||[tipLabel(t)],at:r.at||null};}
  function demoList(){return DEMO_SEED.map(function(r){var n=normalize(r,'demo');n.apiaryId=String(r.apiaryId||'none');n.apiaryName=r.apiaryName||'Arılık';n.hiveName=r.hiveName||(n.kind==='kamera'?tipLabel(r.tip):'Cihaz');return n;});}
  function liveList(){var x={};readArray(DEVICES_KEY).concat(readArray(DISCOVERED_KEY)).forEach(function(r){var n=normalize(r,'user');if(n)x[n.id]=n;});return Object.keys(x).map(function(k){return x[k];});}
  function listDevices(){return isDemo()?demoList():liveList();} function cameraDevices(){return listDevices().filter(function(d){return d.kind==='kamera';});}
  function summary(a){var c={yok:0,bagli:0,kopuk:0,arizali:0,total:a.length};a.forEach(function(d){c[d.status]!=null?c[d.status]++:c.yok++;});return c;}
  function summarize(){return summary(listDevices());} function summarizeCameras(){return summary(cameraDevices());}
  function badge(s){if(!s.total)return{text:'Yok',tone:'tan'};return{text:String(isLive()?(s.bagli>0?s.bagli:s.total):s.total),tone:s.arizali?'red':s.kopuk?'tan':'green'};}
  function anaCihazBadge(){return badge(summarize());} function anaKameraBadge(){return badge(summarizeCameras());}
  function ensureBannerStyles(){if(typeof document==='undefined'||document.getElementById('superari-demo-banner-style'))return;var s=document.createElement('style');s.id='superari-demo-banner-style';s.textContent='.status-pill.status-yok{background:#f1f3f5;color:#868e96;border-color:#ced4da}.status-pill.status-bagli{background:#ebfbee;color:#2b8a3e;border-color:#8ce99a}.status-pill.status-kopuk{background:#fff4e6;color:#e67700;border-color:#ffc078}.status-pill.status-arizali{background:#fff5f5;color:#c92a2a;border-color:#ffa8a8}';(document.head||document.documentElement).appendChild(s);}
  function syncDemoBanner(){if(typeof document==='undefined')return;ensureBannerStyles();try{document.documentElement.setAttribute('data-work-mode',getMode());}catch(e){}}
  global.SuperAriDevices={MODE_KEY:MODE_KEY,DEVICES_KEY:DEVICES_KEY,DISCOVERED_KEY:DISCOVERED_KEY,STATUS:STATUS,TIP_LABELS:TIP_LABELS,DEMO_SEED:DEMO_SEED,getMode:getMode,setMode:setMode,isDemo:isDemo,isLive:isLive,statusLabel:statusLabel,statusTone:statusTone,statusAnaTone:statusAnaTone,tipLabel:tipLabel,isCameraTip:isCameraTip,isApiaryTip:isApiaryTip,listDevices:listDevices,cameraDevices:cameraDevices,summarize:summarize,summarizeCameras:summarizeCameras,anaCihazBadge:anaCihazBadge,anaKameraBadge:anaKameraBadge,syncDemoBanner:syncDemoBanner,ensureBannerStyles:ensureBannerStyles};syncDemoBanner();
})(typeof window!=='undefined'?window:this);
(function(){try{if(typeof document==='undefined')return;function apply(){if(!document.getElementById('weatherStrip')||!document.getElementById('grid')||document.getElementById('ana-safe-layout-css'))return;var s=document.createElement('style');s.id='ana-safe-layout-css';s.textContent=['#grid{flex:0 0 auto!important;grid-template-rows:repeat(4,122px)!important;gap:5px!important}','#weatherStrip{flex:1 1 auto!important;min-height:0!important;display:flex!important;flex-direction:column!important;overflow:visible!important}','#weatherStrip .forecast{flex:1 1 auto!important;min-height:0!important}','#weatherStrip .weather-top{flex:0 0 auto!important}','#muayeneHint.muayene-hint.is-idle{flex:0 0 auto!important;flex-shrink:0!important;overflow:visible!important}','#muayeneHint .muayene-hint-mid{overflow:visible!important}','.muayene-hint-mid .bee-podium{top:auto!important;bottom:calc(100% + 36px)!important;left:50%!important;transform:translateX(-50%)!important;margin:0!important;z-index:8!important;flex-direction:column-reverse!important;gap:2px!important}','.bee-podium .podium-name{overflow:visible!important;z-index:8!important}'].join('');(document.head||document.documentElement).appendChild(s);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();}catch(e){}})();
(function(){try{if(typeof document==='undefined')return;function scan(){var a=document.querySelectorAll('.day-temps');for(var i=0;i<a.length;i++){var t=a[i].textContent.match(/^\\s*(\\d+)\\s*°\\s*\\/\\s*(\\d+)\\s*°\\s*$/);if(t&&a[i].innerHTML.indexOf('class=')===-1)a[i].textContent=t[2]+'°/'+t[1]+'°';}}function start(){scan();var r=document.getElementById('weatherStrip')||document.body;if(r&&typeof MutationObserver!=='undefined')new MutationObserver(scan).observe(r,{childList:true,subtree:true,characterData:true});}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();}catch(e){}})();