/* Bakım akışı sesli komut / miktar çözümleyici. */
const assert = require('assert');
const A = require('../bakim-akis.js');
const eq = (s, exp) => { const r = A.parseCmd(s); Object.keys(exp).forEach((k) => assert.strictEqual(r[k], exp[k], s + ' → ' + JSON.stringify(r))); };
eq('bir buçuk kilo', { n: 1.5, unit: 'kg' });
eq('1,5 kg', { n: 1.5, unit: 'kg' });
eq('2.5 litre', { n: 2.5, unit: 'L' });
eq('yarım kilo', { n: 0.5, unit: 'kg' });
eq('on iki şerit', { n: 12, unit: 'serit' });
eq('iki yüz elli gram', { n: 250, unit: 'g' });
eq('bir virgül beş litre', { n: 1.5, unit: 'L' });
eq('Üç buçuk kilo.', { n: 3.5, unit: 'kg' });
eq('tamam', { cmd: 'tamam' });
eq('evet', { cmd: 'tamam' });
eq('az', { cmd: 'az' });
eq('çok', { cmd: 'cok' });
eq('uygun', { cmd: 'uygun' });
eq('atla', { cmd: 'atla' });
eq('geri', { cmd: 'geri' });
eq('sonraki kovan', { cmd: 'sonraki' });
eq('bir daha', { cmd: 'tekrar' });
eq('ikinci', { ord: 2 });
assert.strictEqual(A.parseCmd('biraz').none, true);
assert.strictEqual(A.convert(250, 'g', 'kg'), 0.25);
assert.strictEqual(A.convert(2, 'kg', 'L'), null);
assert.strictEqual(A.sayNum(1.5), '1 buçuk');
assert.strictEqual(A.sayNum(0.5), 'yarım');

/* Kovan sonu: «Sonraki kovan», «Bitir», «Kovan … geç» (koloni-62) */
const NUMS = ['6219', '101', '105', '12', '42', '6205', '118', '211', '4083'];
const G = (t) => A.parseGoto(t, NUMS);
assert.deepStrictEqual(A.numberGroups('altmış iki on dokuz'), ['62', '19']);
assert.deepStrictEqual(A.numberGroups('altı bin iki yüz on dokuz'), ['6219']);
assert.deepStrictEqual(A.numberGroups("6219'a geç"), ['6219']);
assert.deepStrictEqual(A.numberGroups('iki yüz on bir'), ['211']);
assert.deepStrictEqual(G("6219'a geç"), { cmd: 'goto', no: '6219', known: true });
assert.deepStrictEqual(G('6219a geç'), { cmd: 'goto', no: '6219', known: true });
assert.deepStrictEqual(G('altmış iki on dokuza geç'), { cmd: 'goto', no: '6219', known: true });
assert.deepStrictEqual(G('Altmış iki on dokuza geç'), { cmd: 'goto', no: '6219', known: true });
assert.deepStrictEqual(G('altı bin iki yüz on dokuza geç'), { cmd: 'goto', no: '6219', known: true });
assert.deepStrictEqual(G('altı iki bir dokuz'), { cmd: 'goto', no: '6219', known: true });
assert.deepStrictEqual(G('kovan yüz bire geç'), { cmd: 'goto', no: '101', known: true });
assert.deepStrictEqual(G('yüz beşe geç'), { cmd: 'goto', no: '105', known: true });
assert.deepStrictEqual(G('on ikiye geç'), { cmd: 'goto', no: '12', known: true });
assert.deepStrictEqual(G('kırk ikiye geç'), { cmd: 'goto', no: '42', known: true });
assert.deepStrictEqual(G('altmış iki sıfır beşe geç'), { cmd: 'goto', no: '6205', known: true });
assert.deepStrictEqual(G('iki yüz on bire geç'), { cmd: 'goto', no: '211', known: true });
assert.deepStrictEqual(G('kırk sekiz seksen üçe geç'), { cmd: 'goto', no: '4883', known: false });
assert.deepStrictEqual(G('sonraki'), { cmd: 'sonraki' });
assert.deepStrictEqual(G('sonraki kovan'), { cmd: 'sonraki' });
assert.deepStrictEqual(G('sıradaki'), { cmd: 'sonraki' });
assert.deepStrictEqual(G('bitir'), { cmd: 'bitir' });
assert.deepStrictEqual(G('tamam bitti'), { cmd: 'bitir' });
assert.deepStrictEqual(G('başka kovan'), { cmd: 'liste' });
assert.strictEqual(G('merhaba'), null);
assert.strictEqual(G(''), null);
console.log('bakim-akis-parser: ok');
