/* k101/k104: alt menu cerceve dibinde; Ana hava karti kuculmez; viewport fixed yok */
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const nav = fs.readFileSync(path.join(root, 'nav.js'), 'utf8');
const fit = nav.slice(nav.indexOf('function fitIphone12Shell'), nav.indexOf('function ensureStatusStrip')).replace(/\/\*[\s\S]*?\*\//g, '');
assert.ok(!/global\.visualViewport|vv\.height/.test(fit), 'fit must not size from visualViewport (pinch-zoom/klavye)');
assert.ok(nav.includes('k105') && nav.includes('layoutPhoneStage(phone, 1)'), 'birebir 390x844 stage');
assert.ok(!nav.includes("visualViewport.addEventListener('scroll'"), 'no vv scroll listener');
assert.ok(nav.includes('position:relative!important') && nav.includes('.phone>nav.tabbar'), 'tabbar in frame');
assert.ok(nav.includes('saPhoneStage'), 'phone stage');
assert.ok(nav.includes('.phone>.screen>*{flex-shrink:0!important;}'), 'screen children no shrink');
assert.ok(nav.includes('.phone>.screen>#weatherStrip') && nav.includes('min-height:min-content!important'), 'Ana weather keeps content height');
assert.ok(nav.includes('.phone>nav.tabbar{position:relative!important'), 'tabbar flex sibling at bottom');
const bk = fs.readFileSync(path.join(root, 'bk-kabuk.css'), 'utf8');
assert.ok(bk.includes('k104:'), 'bk k104');
const dr = fs.readFileSync(path.join(root, 'device-runtime.js'), 'utf8');
assert.ok(dr.includes('LOCKED 2026-09-23'), 'locked Ana safe layout untouched');
console.log('k101-nav-bottom ok');
