/* k99: iPhone12 kabugu + ses normal hizi; k100 dinamik fill ile uyumlu */
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const nav = fs.readFileSync(path.join(root, 'nav.js'), 'utf8');
assert.ok(nav.includes('fitIphone12Shell'), 'fitIphone12Shell');
assert.ok(nav.includes('sa-iphone12'), 'sa-iphone12 class');
assert.ok(nav.includes('width:390px!important') && nav.includes('height:844px!important'), 'desktop 390x844 base');
assert.ok(nav.includes('saPhoneStage') && nav.includes('border-radius:44px!important'), 'framed shell');
assert.ok(nav.includes('.phone>.status-bar{display:flex!important'), 'status bar visible in shell');
assert.ok(!/if \(isAnaPage\(\) && !isShotMode\(\)\) return/.test(nav), 'Ana no longer skips strip');
assert.ok(!/if \(isPhoneMobile\(\) && !isShotMode\(\)\) return/.test(nav), 'phone no longer skips strip');
assert.ok(nav.includes("scale('") && nav.includes('fitIphone12Shell'), 'desktop scale keep');
const bk = fs.readFileSync(path.join(root, 'bk-kabuk.css'), 'utf8');
assert.ok(bk.includes('k100:') || bk.includes('k99:'), 'bk shell marker');
assert.ok(bk.includes('100dvh') || bk.includes('390px'), 'bk phone size');
const ses = fs.readFileSync(path.join(root, 'sesle-muayene.js'), 'utf8');
assert.ok(ses.includes('normal: 1.12'), 'normal rate 1.12');
assert.ok(ses.includes('hizli: 1.28'), 'hizli rate 1.28');
assert.ok(ses.includes("RATE_KEY = 'superari.sesleHiz.v1'"), 'rate key kept');
console.log('k99-iphone12-shell-rate ok');
